### ISSUE TITLE
Don't force Content-type for valid WSDL

### ISSUE THREAD

**Issue by rymo** [moszeed/wsdlrdr#3]
An error is thrown in function `getWsdl` if `xml` and `wsdl` are both missing from the Content-type header of a retrieved WSDL document, even if the body is otherwise valid.

Can this be a warning instead? Try to continue ahead with parsing the body so that misconfigured servers (with something silly like `text/plain`) will not prevent one from consuming the service.

**Comment by moszeed** [comment]
i added a "failOnWrongContentType" option with version 0.4.0 =)
